#+title: 一步步精通Docker容器实战
* Docker简介
file:./img/docker/docker.png

[[https://docs.docker.com/][Docker相关文档]]

* CentOS7安装和基本使用
** 虚拟机中安装CentOS7
** 备份安装镜像和通过VMware制作快照
** Windows下远程连接CentOS7
** Linux下远程连接CentOS7
#+begin_src sh
ssh root@192.168.1.105
#输入密码
#切换到root用户
su root
#输入root密码
#退出root账户进入user账户
exit
#再输入exit断开远程连接
#+end_src
* Docker CE安装
** Docker CE
#+begin_src sh
$ sudo yum install -y yum-utils
$ sudo yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo
#$ sudo yum-config-manager --enable docker-ce-edge
#禁用
$ sudo yum-config-manager --disable docker-ce-edge
$ sudo yum makecache fast
$ sudo yum install docker-ce
#$ sudo yum install docker-ce-<VERSION>
#$ yum list docker-ce.x86_64 --showduplicates |sort -r docker-ce.x86_64 17.03.0.el7 docker-ce-stable  
$ sudo systemctl start docker
$ sudo docker run hello-world
#+end_src
* Docker特点

file:./img/docker/docker_SaaS.png

file:./img/docker/SaaS.jpg

1.更快速的交付和部署

2.更高效的虚拟化

3.更轻松的迁移和扩展

4.更简单的管理
** 虚拟化技术比较
容器相比虚拟机更轻量

*** 虚拟机

file:./img/docker/VM.png

*** 容器

file:./img/docker/Containe.png

* Docker结构和组成
** 结构和组成

file:./img/docker/architecture.svg

file:./img/docker/client_daemon_hub.png

客户端服务端模式可单机可分布式部署

服务端负责docker镜像的构建，运行，发布.

*** The Docker daemon

接收Docker API请求和管理docker的对象例如镜像、容器、网络、存储卷等，

也可以和其他的Docker daemon通信管理docker的service

*** The Docker client

可以和多个daemon进行通信，发送指令给daemon, 用户和daemon交互主要方式。

*** Docker registries

存储docker镜像,Docker Cloud是一个公共仓库,是docker默认的仓库。

可以搭建私有仓库。

docker Cloud有docker可信仓库。

拉取，推送镜像到设定仓库。

Docker store允许用户购买和出售自己的镜像，也可以免费发布自己的镜像。

*** Docker objects

在使用docker的时候，将会涉及到创建、使用镜像、容器、网络、卷、插件或者其他的对象。

** 指令

#+begin_src sh

Management Commands:
  container   Manage containers
  image       Manage images
  network     Manage networks
  node        Manage Swarm nodes
  plugin      Manage plugins
  secret      Manage Docker secrets
  service     Manage services
  stack       Manage Docker stacks
  swarm       Manage Swarm
  system      Manage Docker
  volume      Manage volumes

Commands:
  attach      Attach to a running container
  build       Build an image from a Dockerfile
  commit      Create a new image from a container's changes
  cp          Copy files/folders between a container and the local filesystem
  create      Create a new container
  diff        Inspect changes to files or directories on a container's filesystem
  events      Get real time events from the server
  exec        Run a command in a running container
  export      Export a container's filesystem as a tar archive
  history     Show the history of an image
  images      List images
  import      Import the contents from a tarball to create a filesystem image
  info        Display system-wide information
  inspect     Return low-level information on Docker objects
  kill        Kill one or more running containers
  load        Load an image from a tar archive or STDIN
  login       Log in to a Docker registry
  logout      Log out from a Docker registry
  logs        Fetch the logs of a container
  pause       Pause all processes within one or more containers
  port        List port mappings or a specific mapping for the container
  ps          List containers
  pull        Pull an image or a repository from a registry
  push        Push an image or a repository to a registry
  rename      Rename a container
  restart     Restart one or more containers
  rm          Remove one or more containers
  rmi         Remove one or more images
  run         Run a command in a new container
  save        Save one or more images to a tar archive (streamed to STDOUT by default)
  search      Search the Docker Hub for images
  start       Start one or more stopped containers
  stats       Display a live stream of container(s) resource usage statistics
  stop        Stop one or more running containers
  tag         Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE
  top         Display the running processes of a container
  unpause     Unpause all processes within one or more containers
  update      Update configuration of one or more containers
  version     Show the Docker version information
  wait        Block until one or more containers stop, then print their exit codes

#+end_src

#+begin_src sh

[root@localhost user]# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.03.1-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.688 GiB
Name: localhost.localdomain
ID: SA42:IFVV:F4SK:QLB6:PDW2:3QBQ:SRUF:ZZMN:TE4T:62XY:OFXB:I43I
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: bvok
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
[root@localhost user]# 


#+end_src

#+begin_src sh

[root@localhost lib]# pwd
/var/lib
[root@localhost lib]# tree docker -L 4
docker
├── containers
├── image
│   └── overlay
│       ├── distribution
│       │   ├── diffid-by-digest
│       │   └── v2metadata-by-diffid
│       ├── imagedb
│       │   ├── content
│       │   └── metadata
│       ├── layerdb
│       │   ├── mounts
│       │   ├── sha256
│       │   └── tmp
│       └── repositories.json
├── network
│   └── files
│       └── local-kv.db
├── overlay
│   ├── 9c624a3534090b0ef2c78352487c2d35e238ac00e674015124f50092bb1f512c
│   │   └── root
│   │       ├── bin
│   │       ├── dev
│   │       ├── etc
│   │       ├── home
│   │       ├── root
│   │       ├── tmp
│   │       ├── usr
│   │       └── var
│   ├── b06d7c2247c2d8327c1154536527022b5c882d9e2281decf13923718e8099205
│   │   └── root
│   │       ├── bin
│   │       ├── dev
│   │       ├── etc
│   │       ├── home
│   │       ├── root
│   │       ├── tmp
│   │       ├── usr
│   │       └── var
│   └── b2ccaa0fb436955c68d344848036c4407481c276a66501f9b5531164eefbac46
│       └── root
│           ├── bin
│           ├── dev
│           ├── etc
│           ├── home
│           ├── root
│           ├── tmp
│           ├── usr
│           └── var
├── plugins
│   ├── storage
│   │   └── blobs
│   │       └── tmp
│   └── tmp
├── swarm
├── tmp
├── trust
└── volumes
    └── metadata.db

55 directories, 3 files
[root@localhost lib]# 

#+end_src

** 镜像

一般基于其他镜像，并添加自定义部分，分层构建，保留历史，构建每层结束的时候，不需要的清除，不包括动态数据。

不是整体打包的内容，而是一层层组成的。可以理解为用来创建容器的只读模板。

#+begin_src sh

[root@localhost docker]# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
vker/websv          0.1                 57ce173fc558        2 days ago          7.22 MB
busybox             latest              54511612f1c4        2 weeks ago         1.13 MB
[root@localhost docker]# docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                      PORTS               NAMES
08135140ff81        vker/websv:0.1      "sh"                39 seconds ago      Exited (0) 12 seconds ago                       websv1
[root@localhost docker]# tree -L 4
......
[root@localhost docker]# 

#+end_src

#+begin_src sh

[root@localhost overlay]# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
vker/websv          0.1                 57ce173fc558        2 days ago          7.22 MB
busybox             latest              54511612f1c4        2 weeks ago         1.13 MB
[root@localhost overlay]# pwd
/var/lib/docker/image/overlay
[root@localhost overlay]# tree -L 4
......
[root@localhost overlay]# 

#+end_src

演示

自己可以创建镜像和发布镜像，或者使用第三方发布到仓库的镜像，

自己创造镜像需要使用规定的语法编写Dockerfile文件然后执行构建，每个执行命令都会创建一层。

如果修改了Dockerfile并重新构建镜像，只有被修改的层才会被重新构建，这样构建很快，轻量，小型。

Dockerfile

#+begin_src sh
# Comment
INSTRUCTION arguments

FROM
RUN
CMD
LABEL
EXPOSE
ENV
ADD
COPY
ENTRYPOINT
VOLUME
USER
WORKDIR
ARG
ONBUILD
STOPSIGNAL
HEALTHCHECK
SHELL
#+end_src

golang web源码


#+begin_src golang
package main
import (
    "fmt"
    "net/http"
    "log"
    "time"
    "os"
)
func hello(w http.ResponseWriter, r *http.Request) {
    host, err := os.Hostname()
    if err != nil {
        fmt.Printf("%s", err)
    } else {
    fmt.Fprintf(w, time.Now().Format("2006-01-02 15:04:05 -0700"))
    fmt.Fprintf(w,"\n")
    fmt.Fprintf(w, host)
    }
    fmt.Println()
}
func main() {
    http.HandleFunc("/", hello) //设置访问的路由
    err := http.ListenAndServe("0.0.0.0:8080", nil) //设置监听的端口
    if err != nil {
        log.Fatal("ListenAndServe: ", err)
    }
}
#+end_src

Dockerfile源码

#+begin_src sh



#+end_src

构建

#+begin_src sh

[root@localhost app]# docker build -t vker/websvbase:0.1 .
......
[root@localhost app]# cat Dockerfile 
......
#+end_src

#+begin_src sh

[root@localhost app]# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
vker/websvbase      0.1                 4b8ff495d4c5        11 minutes ago      6.09 MB
vker/websv          0.1                 57ce173fc558        2 days ago          7.22 MB
busybox             latest              54511612f1c4        2 weeks ago         1.13 MB
[root@localhost app]# docker inspect 4b
...... 

#+end_src

修改Dockerfile后再进行构建

#+begin_src sh

[root@localhost app]# docker build -t vker/websvbase:0.2 .
......

#+end_src


演示构建简单镜像并留作业

*** 重点镜像

scratch:一个空镜像，特别是用于“从头开始”构建镜像。

busybox:小镜像，适合静态编译的不依赖操作系统环境的二进制程序，演示golang编译web程序并运行在busybox下。

busybox:uclibc (微 嵌入)  busybox:glibc (GNU)  busybox:musl(嵌入)

alpine:5M左右，带有软件安装功能的小镜像，很适合做为基础镜像。

clearlinux:针对intel架构优化，面向云端的linux系统。

练习alpine环境下运行golang web程序


** 容器

从镜像创建的运行实例，启动、开始、停止、删除，相当于一个完整的linux操作系统，相互隔离、保证安全，运行应用。

可以将一个容器接入多个网络，可以挂载存储，可以基于当前状态容器创建镜像。


容器运行->停止->删除 路径变化

#+begin_src sh

[root@localhost docker]# tree -L 4
......
[root@localhost docker]# ls
containers  image  network  overlay  plugins  swarm  tmp  trust  volumes
[root@localhost docker]# docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                    NAMES
08135140ff81        vker/websv:0.1      "sh"                34 minutes ago      Up 28 minutes       0.0.0.0:8080->8080/tcp   websv1
[root@localhost docker]# docker stop 08
08
[root@localhost docker]# 
[root@localhost docker]# docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                       PORTS               NAMES
08135140ff81        vker/websv:0.1      "sh"                34 minutes ago      Exited (137) 7 seconds ago                       websv1
[root@localhost docker]# tree -L 4
......
[root@localhost docker]# docker rm 08
08
[root@localhost docker]# tree -L 4
......
#+end_src


镜像是只读的，容器在启动的时候创建一层可写层作为最上层。

可以从一个镜像创建多个隔离的互不干扰的容器。

分配一个读写区作为最后一层。

网络默认直接使用NAT转换。


** 仓库

*** 公有仓库

最大的公开仓库是Docker Hub

演示提交镜像到Docker Hub

国内Docker Hub仓库镜像服务器，同时也可以上传自己的镜像

阿里[[https://dev.aliyun.com/search.html][https://dev.aliyun.com/search.html]]

*** 私有仓库

自己搭建

** SERVICES

swarm

* 数据管理
** 镜像文件系统
** 挂载

* 网络管理
